### ISSUE TITLE
Security warning on link in README

### ISSUE THREAD

**Issue by BeckmaR** [leonliangsun/simhash#21]
The following link: https://leons.im/posts/a-python-implementation-of-simhash-algorithm/ gives me a security warning in chrome with `NET::ERR_CERT_DATE_INVALID`.

**Comment by leonliangsun** [comment]
Please switch to `http`. The `https` certificate expired. Because I previously used StartSSL as the SSL certificate, which proves not secure recently, so I'm still searching for alternative SSL provider.

**Comment by leonliangsun** [comment]
Link updated.
